<a href="https://colab.research.google.com/github/DineshDevPandey/Pytorch_basics/blob/master/4_pytorch_tensor_3d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# 3D Tensor initialization 


In [3]:
three_d = torch.arange(18).view(3,2,3)
three_d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

# 3D tensor slicing

In [4]:
three_d[1, 1, 1]

tensor(10)

In [5]:
three_d[2][1][2]

tensor(17)

In [6]:
three_d[2, 1:, :]

tensor([[15, 16, 17]])

# 3D tensor arithmetic

In [7]:
three_d_1 = torch.arange(18).view(3,2,3)
three_d_1

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [8]:
three_d_2 = torch.arange(10, 28).view(3,2,3)
three_d_2

tensor([[[10, 11, 12],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]],

        [[22, 23, 24],
         [25, 26, 27]]])

In [9]:
three_d_sum = three_d_1 + three_d_2
three_d_sum

tensor([[[10, 12, 14],
         [16, 18, 20]],

        [[22, 24, 26],
         [28, 30, 32]],

        [[34, 36, 38],
         [40, 42, 44]]])

In [10]:
three_d_mul = three_d_1 * three_d_2
three_d_mul

tensor([[[  0,  11,  24],
         [ 39,  56,  75]],

        [[ 96, 119, 144],
         [171, 200, 231]],

        [[264, 299, 336],
         [375, 416, 459]]])