<a href="https://colab.research.google.com/github/DineshDevPandey/Pytorch_basics/blob/master/5_pytorch_mat_mult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# matrix multiplication

In [2]:
mat_a = torch.arange(6).view(2, 3)
mat_a  

tensor([[0, 1, 2],
        [3, 4, 5]])

In [5]:
mat_b = torch.arange(10, 16).view(3, 2)
mat_b

tensor([[10, 11],
        [12, 13],
        [14, 15]])

In [6]:
mat_mul = torch.matmul(mat_a, mat_b)
mat_mul

tensor([[ 40,  43],
        [148, 160]])

alternate 

In [7]:
mat_a @ mat_b

tensor([[ 40,  43],
        [148, 160]])