<a href="https://colab.research.google.com/github/DineshDevPandey/Pytorch_basics/blob/master/7_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

## Basic idea of linear regression

**Linear Regression :** LR tries to find a optimal line/ plane/ hyperplane which can seperate out classes in dataset. <br>
Genaral equation of plane is **y = w<sup>T</sup>x + b**

In [0]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
  y = w*x + b
  return y

In [15]:
x = torch.tensor([[2], [3]])
print(forward(x))

tensor([[ 7],
        [10]], grad_fn=<AddBackward0>)


## Better Implementation of LR


In [0]:
from torch.nn import Linear

In [18]:
torch.manual_seed(1)

# linear model takes two param num of input , num of output
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [20]:
x = torch.tensor([[3.0], [4.4]])
print(model(x))

tensor([[1.1044],
        [1.8258]], grad_fn=<AddmmBackward>)


## Even better implementation of LR

In [0]:
import torch.nn as nn

# nn.module is a base class for all neural network models

class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
    
  def forward(self, x):
    pred = self.linear(x)
    return pred
    

In [35]:
torch.manual_seed(4)
model = LR(1, 1)

x = torch.tensor([[3.0], [4.0]])
model.forward(x)

tensor([[0.4760],
        [0.5953]], grad_fn=<AddmmBackward>)