<a href="https://colab.research.google.com/github/DineshDevPandey/Pytorch_basics/blob/master/pytorch_tensor_2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# 2D tensor

In [9]:
one_d = torch.arange(1, 10)
one_d

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
two_d = one_d.view(3, 3)
two_d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
two_d.dim()

2

# 2D tensor slicing

In [13]:
two_d[0]

tensor([1, 2, 3])

In [15]:
two_d[1, 2]

tensor(6)

In [17]:
two_d[1][2]

tensor(6)

In [20]:
two_d[1:, 1:]

tensor([[5, 6],
        [8, 9]])

# 2D tensor arithmetic

In [29]:
_2d_1 = torch.arange(4).view(2, -1)  
print(_2d_1)

_2d_2 = torch.arange(4, 8).view(2, -1)  
print(_2d_2)

tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])


In [33]:
_2d_sum = _2d_1 + _2d_2
print(_2d_sum)

_2d_sum = _2d_1 * _2d_2
print(_2d_sum)


tensor([[ 4,  6],
        [ 8, 10]])
tensor([[ 0,  5],
        [12, 21]])


# 3D tensor

In [23]:
three_d = torch.arange(18).view(3,3,2)
three_d

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [24]:
three_d = torch.arange(18).view(2, 3, 3)
three_d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])