<a href="https://colab.research.google.com/github/DineshDevPandey/Pytorch_basics/blob/master/pytorch_tensor_1d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install pytorch

In [1]:
# install torch
!pip install torch

In [0]:
import torch
import numpy as np

# Create a 1 D tensor




In [4]:
a = torch.tensor([1, 2, 3, 4])
a

tensor([1, 2, 3, 4])

In [5]:
a.dtype

torch.int64

# Tensor element access and slicing

In [6]:
a[2]

tensor(3)

In [8]:
a[2: 4]

tensor([3, 4])

In [25]:
a[::1]

tensor([1, 2, 3, 4])

In [24]:
a[::2]

tensor([1, 3])

In [26]:
a[::-1]

ValueError: ignored

# Float Tensor

In [0]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])

In [10]:
f

tensor([1., 2., 3., 4., 5., 6.])

In [11]:
f.dtype

torch.float32

# Reshape tensor

In [12]:
f.view(6, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [13]:
f.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
f.view(3, -1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [15]:
f.view(7, 1)

RuntimeError: ignored

# Tensor to numpy conversion

In [19]:
n = np.array([1, 2, 3, 4, 5])
tensor_n = torch.from_numpy(n)
print(tensor_n)
print(tensor_n.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


# Numpy to tensor conversion

In [21]:
numpy_n = tensor_n.numpy()
print(numpy_n)
print(numpy_n.dtype)

[1 2 3 4 5]
int64
